

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData Unknown                                    /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

    
  $data.Entity.extend('MSNAdmin.Models.CITY', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'CITYAREAs': { 'type':'Array','elementType':'MSNAdmin.Models.CITYAREA' },
     'USERINFOes': { 'type':'Array','elementType':'MSNAdmin.Models.USERINFO' }
  });

  $data.Entity.extend('MSNAdmin.Models.CITYAREA', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'DESCRIPTION': { 'type':'Edm.String' },
     'CITYID': { 'type':'Edm.Decimal' },
     'CITY': { 'type':'MSNAdmin.Models.CITY' },
     'USERINFOes': { 'type':'Array','elementType':'MSNAdmin.Models.USERINFO' }
  });

  $data.Entity.extend('MSNAdmin.Models.MEMBERSHIP', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'DESCRIPTION': { 'type':'Edm.String' },
     'USERMEMBERSHIPs': { 'type':'Array','elementType':'MSNAdmin.Models.USERMEMBERSHIP' }
  });

  $data.Entity.extend('MSNAdmin.Models.SERVICEBID', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'USERID': { 'type':'Edm.Decimal' },
     'USERSERVICENEEDID': { 'type':'Edm.Decimal' },
     'BIDTITLE': { 'type':'Edm.String' },
     'BIDDESCRIPTION': { 'type':'Edm.String' },
     'BIDAMOUNT': { 'type':'Edm.Decimal' },
     'USERINFO': { 'type':'MSNAdmin.Models.USERINFO' },
     'USERSERVICENEED': { 'type':'MSNAdmin.Models.USERSERVICENEED' },
     'USERSERVICENEEDs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICENEED' }
  });

  $data.Entity.extend('MSNAdmin.Models.SERVICECATEGORY', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'DESCRIPTION': { 'type':'Edm.String' },
     'SERVICESUBCATEGORies': { 'type':'Array','elementType':'MSNAdmin.Models.SERVICESUBCATEGORY' },
     'USERSERVICEs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICE' },
     'USERSERVICENEEDs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICENEED' }
  });

  $data.Entity.extend('MSNAdmin.Models.SERVICESTATE', {
     'ID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'DESCRIPTION': { 'type':'Edm.String' },
     'USERSERVICENEEDs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICENEED' }
  });

  $data.Entity.extend('MSNAdmin.Models.SERVICESUBCATEGORY', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'DESCRIPTION': { 'type':'Edm.String' },
     'SERVICECATEGORYID': { 'type':'Edm.Decimal' },
     'SERVICECATEGORY': { 'type':'MSNAdmin.Models.SERVICECATEGORY' },
     'USERSERVICEs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICE' },
     'USERSERVICENEEDs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICENEED' }
  });

  $data.Entity.extend('MSNAdmin.Models.SERVICETIMETYPE', {
     'ID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'DESCRIPTION': { 'type':'Edm.String' },
     'USERSERVICENEEDs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICENEED' }
  });

  $data.Entity.extend('MSNAdmin.Models.SOCIALLOGIN', {
     'ID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'DESCRIPTION': { 'type':'Edm.String' },
     'USERINFOes': { 'type':'Array','elementType':'MSNAdmin.Models.USERINFO' }
  });

  $data.Entity.extend('MSNAdmin.Models.USERBID', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'USERID': { 'type':'Edm.Decimal' },
     'BIDS': { 'type':'Edm.Int32' },
     'USERINFO': { 'type':'MSNAdmin.Models.USERINFO' }
  });

  $data.Entity.extend('MSNAdmin.Models.USERFUND', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'USERID': { 'type':'Edm.Decimal' },
     'BALANCE': { 'type':'Edm.Decimal' },
     'USERINFO': { 'type':'MSNAdmin.Models.USERINFO' }
  });

  $data.Entity.extend('MSNAdmin.Models.USERINFO', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'NAME': { 'type':'Edm.String' },
     'EMAIL': { 'type':'Edm.String' },
     'PHONE': { 'type':'Edm.String' },
     'CITYID': { 'type':'Edm.Decimal' },
     'CITYAREAID': { 'type':'Edm.Decimal' },
     'LOGINTYPEID': { 'type':'Edm.Int32' },
     'CURRENTLOCATION': { 'type':'Edm.String' },
     'CITY': { 'type':'MSNAdmin.Models.CITY' },
     'CITYAREA': { 'type':'MSNAdmin.Models.CITYAREA' },
     'SERVICEBIDs': { 'type':'Array','elementType':'MSNAdmin.Models.SERVICEBID' },
     'SOCIALLOGIN': { 'type':'MSNAdmin.Models.SOCIALLOGIN' },
     'USERBIDS': { 'type':'Array','elementType':'MSNAdmin.Models.USERBID' },
     'USERFUNDS': { 'type':'Array','elementType':'MSNAdmin.Models.USERFUND' },
     'USERMEMBERSHIPs': { 'type':'Array','elementType':'MSNAdmin.Models.USERMEMBERSHIP' },
     'USERSERVICEs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICE' },
     'USERSERVICENEEDs': { 'type':'Array','elementType':'MSNAdmin.Models.USERSERVICENEED' }
  });

  $data.Entity.extend('MSNAdmin.Models.USERMEMBERSHIP', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'USERID': { 'type':'Edm.Decimal' },
     'MEMBERSHIPID': { 'type':'Edm.Decimal' },
     'COMMENTS': { 'type':'Edm.String' },
     'MEMBERSHIP': { 'type':'MSNAdmin.Models.MEMBERSHIP' },
     'USERINFO': { 'type':'MSNAdmin.Models.USERINFO' }
  });

  $data.Entity.extend('MSNAdmin.Models.USERSERVICE', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'USERID': { 'type':'Edm.Decimal' },
     'SERVICECATEGORYID': { 'type':'Edm.Decimal' },
     'SERVICESUBCATEGORYID': { 'type':'Edm.Decimal' },
     'SERVICECATEGORY': { 'type':'MSNAdmin.Models.SERVICECATEGORY' },
     'SERVICESUBCATEGORY': { 'type':'MSNAdmin.Models.SERVICESUBCATEGORY' },
     'USERINFO': { 'type':'MSNAdmin.Models.USERINFO' }
  });

  $data.Entity.extend('MSNAdmin.Models.USERSERVICENEED', {
     'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'USERID': { 'type':'Edm.Decimal' },
     'SERVICELOCATION': { 'type':'Edm.String' },
     'SERVICETITLE': { 'type':'Edm.String' },
     'SERVICEDESCRIPTION': { 'type':'Edm.String' },
     'SERVICECATEGORYID': { 'type':'Edm.Decimal' },
     'SERVICESUBCATEGORYID': { 'type':'Edm.Decimal' },
     'MINBUDGET': { 'type':'Edm.Decimal' },
     'MAXBUDGET': { 'type':'Edm.Decimal' },
     'SERVICESTATE': { 'type':'Edm.Int32' },
     'SERVICETIMETYPE': { 'type':'Edm.Int32' },
     'SERVICENEEDEDDATE': { 'type':'Edm.DateTimeOffset' },
     'ALLOCATEDBIDID': { 'type':'Edm.Decimal' },
     'SERVICEBIDs': { 'type':'Array','elementType':'MSNAdmin.Models.SERVICEBID' },
     'SERVICEBID': { 'type':'MSNAdmin.Models.SERVICEBID' },
     'SERVICECATEGORY': { 'type':'MSNAdmin.Models.SERVICECATEGORY' },
     'SERVICESTATE1': { 'type':'MSNAdmin.Models.SERVICESTATE' },
     'SERVICESUBCATEGORY': { 'type':'MSNAdmin.Models.SERVICESUBCATEGORY' },
     'SERVICETIMETYPE1': { 'type':'MSNAdmin.Models.SERVICETIMETYPE' },
     'USERINFO': { 'type':'MSNAdmin.Models.USERINFO' }
  });

  $data.EntityContext.extend('Default.Container', {
     'CITies': { type: $data.EntitySet, elementType: MSNAdmin.Models.CITY},
     'CITYAREAs': { type: $data.EntitySet, elementType: MSNAdmin.Models.CITYAREA},
     'MEMBERSHIPs': { type: $data.EntitySet, elementType: MSNAdmin.Models.MEMBERSHIP},
     'SERVICEBIDs': { type: $data.EntitySet, elementType: MSNAdmin.Models.SERVICEBID},
     'SERVICECATEGORies': { type: $data.EntitySet, elementType: MSNAdmin.Models.SERVICECATEGORY},
     'SERVICESTATEs': { type: $data.EntitySet, elementType: MSNAdmin.Models.SERVICESTATE},
     'SERVICESUBCATEGORies': { type: $data.EntitySet, elementType: MSNAdmin.Models.SERVICESUBCATEGORY},
     'SERVICETIMETYPEs': { type: $data.EntitySet, elementType: MSNAdmin.Models.SERVICETIMETYPE},
     'SOCIALLOGINs': { type: $data.EntitySet, elementType: MSNAdmin.Models.SOCIALLOGIN},
     'USERBIDS': { type: $data.EntitySet, elementType: MSNAdmin.Models.USERBID},
     'USERFUNDS': { type: $data.EntitySet, elementType: MSNAdmin.Models.USERFUND},
     'USERINFOes': { type: $data.EntitySet, elementType: MSNAdmin.Models.USERINFO},
     'USERMEMBERSHIPs': { type: $data.EntitySet, elementType: MSNAdmin.Models.USERMEMBERSHIP},
     'USERSERVICEs': { type: $data.EntitySet, elementType: MSNAdmin.Models.USERSERVICE},
     'USERSERVICENEEDs': { type: $data.EntitySet, elementType: MSNAdmin.Models.USERSERVICENEED}
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(Default.Container);
  
      
})(window, $data);
      
    